const INJURIES = [
  {
    id: "27",
    Name: "Bruised Knee",
    DurationMin: 1,
    DurationMax: 3,
    AffectedLow: "Athleticism"
  },
  {
    id: "30",
    Name: "Bruised Shoulder",
    DurationMin: 1,
    DurationMax: 3,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding"
  },
  {
    id: "32",
    Name: "Bruised Tailbone",
    DurationMin: 2,
    DurationMax: 3,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding"
  },
  {
    id: "61",
    Name: "Hyperextended Knee",
    DurationMin: 2,
    DurationMax: 3,
    AffectedLow:
      "Finishing, Shooting, Post Game, Stocks, Rebounding, Athleticism"
  },
  {
    id: "60",
    Name: "Hyperextended Elbow",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding"
  },
  {
    id: "66",
    Name: "Leg Cramp",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Shooting",
    AffectedHigh: "Athleticism",
    DNP: true
  },
  {
    id: "70",
    Name: "Migraine",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Shooting, Rebounding, Post Game, Driving Layup",
    AffectedHigh: "Playmaking, Offensive Consistency,",
    DNP: true
  },
  {
    id: "71",
    Name: "Neck Spasms",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow:
      "Finishing, Shooting, Post Game, Stocks, Rebounding, Athleticism"
  },
  {
    id: "75",
    Name: "Pinched Elbow Nerve",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding"
  },
  {
    id: "77",
    Name: "Pinched Shoulder Nerve",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding"
  },
  {
    id: "78",
    Name: "Plantar Fasciitis",
    DurationMin: 2,
    DurationMax: 5,
    AffectedLow: "Finishing, Post Game, Athleticism"
  },
  {
    id: "85",
    Name: "Shoulder Tendinitis",
    DurationMin: 2,
    DurationMax: 5,
    AffectedLow: "Shooting, Post Game, Finishing, Stocks, Rebounding,"
  },
  {
    id: "86",
    Name: "Sore Ankle",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Shooting, Post Game",
    AffectedHigh: "Finishing, Athletiicsm",
    DNP: true
  },
  {
    id: "89",
    Name: "Sore Hamstring",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
    AffectedHigh: "Athleticism",
    DNP: true
  },
  {
    id: "91",
    Name: "Sore Knee",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
    AffectedHigh: "Athleticism",
    DNP: true
  },
  {
    id: "93",
    Name: "Sore Wrist",
    DurationMin: 3,
    DurationMax: 4,
    AffectedLow: "Finishing, Shooting, Post Game"
  },
  {
    id: "96",
    Name: "Sprained Elbow",
    DurationMin: 3,
    DurationMax: 5,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding"
  },
  {
    id: "104",
    Name: "Strained Achilles",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Athleticism"
  },
  {
    id: "109",
    Name: "Strained MCL",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
    AffectedHigh: "Athleticism",
    DNP: true
  }
];

const twitterAccounts = [
  "AjincaAlexis42",
  "FreeMoAlmond",
  "Giannis_An34",
  "AsikOmer",
  "Gustavo_Ayon15",
  "TheBlurBarbosa",
  "AndreaBargnani",
  "nicolas88batum",
  "marcobelinelli",
  "jonathanbender9",
  "RealKITO",
  "bismackbiyombo",
  "drayblatche",
  "Cbrackins_33",
  "Primozbrezec",
  "MrJonBrockman",
  "D_Brown4",
  "RebuildCaracter",
  "Casspi18",
  "tysonchandler",
  "Victor_Claver",
  "SHERRONCOLLINS4",
  "DC4Three",
  "JoeCrawford5",
  "zayrd1",
  "Goran_Dragic",
  "DevinEbanks3",
  "pewingjr6",
  "christeyenga31",
  "festus",
  "EvanFourmizz",
  "JGidd4",
  "rudygobert27",
  "MGortat",
  "dontegreeneCOS",
  "tgriff32",
  "HamedHaddadi15",
  "bhans23",
  "Tru_Harp32",
  "T_Harris87",
  "chiggins11",
  "NeneHilario42",
  "ParkaySmooth",
  "thoneycutt23",
  "DHorner31",
  "Lester26Hudson",
  "biggame_hunter",
  "Ersan",
  "DBlock_Official",
  "DaTrillStak5",
  "KONJames10",
  "OthyusTheGreat",
  "JonasJerebko",
  "PoohJeter",
  "IamAmirJohnson",
  "AJALLDAY1",
  "KingMe_DJ1",
  "DequanMJones",
  "RealKrisJo",
  "FlightLeslie23",
  "ShaunLivingston",
  "_ScottMachado",
  "vernon_macklin",
  "ianmahinmi",
  "masfresco",
  "EarlThePearl_15",
  "DonatasMot",
  "KMurph_55",
  "BokiNachbar",
  "NerlensNoel3",
  "Bebe92",
  "jermaineoneal",
  "CharlesOakley34",
  "obricio7",
  "zaza27",
  "ImJustPargo",
  "KendrickPerkins",
  "MickaelPietrus",
  "PPrigioni9",
  "dennisrodman",
  "DennisMike93",
  "ThaboSefolosha",
  "french_savage",
  "TokoShengelia23",
  "XavierSilas",
  "Big_G_21",
  "SeanSingletary",
  "JSmith_8",
  "NdotSmitty",
  "Amareisreal",
  "jtaylor8ball",
  "Teletovic33",
  "MychelThompson",
  "DoeTuck",
  "hidoturkoglu15",
  "jeremytyler3",
  "BenoUdrih1",
  "VAREJAOANDERSON",
  "JanVesely24",
  "SashaVujacic",
  "kyleweaver5",
  "MartellWebster",
  "Sonny13",
  "dj_white3",
  "Highway_30",
  "youngwhiteside",
  "Jwilliams20",
  "TeamLou23",
  "TheRealTWill",
  "SamYoung4",
  "LukeZeller40",
  "REALRICKLEDO1",
  "DdotJAY30",
  "Shopson32",
  "daanteee",
  "bosnianbeast27",
  "Bruno_Caboclo",
  "CapelaClint",
  "LeaderOfHorde",
  "DamienINGLIS",
  "waltertavares22",
  "Thanasis_ante43",
  "DangubicNemanja",
  "KarrSampson14",
  "RonaldRoberts5",
  "1DEEBOST",
  "JackCooligan45",
  "EricMoreland15",
  "EGRIFFDASTORY",
  "Damjan_Rudez",
  "Jmyke1",
  "JoshDavis_22",
  "PatricYoung4",
  "44Bojan",
  "JamesDa_Truth",
  "dstockton32",
  "JarellEddie",
  "cprather24",
  "jamilwilson_22",
  "dre_dawkins",
  "Slim_J12",
  "Khem_Birch",
  "LangGalloway10",
  "traviswear",
  "ACraft4",
  "mitchell_watt",
  "aoriakhi42",
  "PAPPYGAWD",
  "Pusha650",
  "brockm12",
  "TarikBlack25",
  "bradyheslip",
  "DeonteBurton",
  "Timfraz23",
  "RodneyMcGruder",
  "Cwat205",
  "Kjay24k",
  "Joeingles7",
  "ajmitchell25",
  "scoesh0w",
  "jerel_mcneal",
  "SeanKilpatrick",
  "alexabrines",
  "RaulTogni",
  "kazemiworld",
  "1JOLOLO",
  "Deshaunthomas_0",
  "satoransky",
  "furkanaldemir19",
  "TomislavZubcic7",
  "ilknkrmn",
  "MizzouMonster12",
  "DBertans_42",
  "NemanjaBjelica",
  "taybowl_",
  "23Llull",
  "pripripri15",
  "cenkakyol",
  "BigSofoGR",
  "Elijah_Millsap",
  "TheRealDrewski1",
  "richxsolo3",
  "cjfair",
  "clutchcrawford3",
  "KarlTowns",
  "Dloading",
  "kporzee",
  "mariohezonja",
  "THEwillieCS15",
  "emmanuelmudiay",
  "iAmSJ",
  "FSKPart3",
  "IAmJustise",
  "Original_Turner",
  "TreyLyles",
  "DevinBook",
  "campayne",
  "KELLYOUBREJR",
  "T_Rozzay3",
  "ShowtimeMr1",
  "dekker",
  "delonwright",
  "JusAnderson1",
  "BPortistime",
  "IAmCHAP24",
  "1Tyus",
  "MartinJarell",
  "NMilutinov",
  "Larrydn22",
  "briskuno",
  "Loon_Rebel5",
  "cediosman",
  "MONSTATREZZ",
  "Jmickey_02",
  "TwoShotOne",
  "willyhg94",
  "R_Xmas25",
  "Rich_Holmes22",
  "DHilliard6X",
  "J_Rich1",
  "JoeyBuckets3",
  "DrewRoc5",
  "M3Thornton",
  "npowell2404",
  "GudaitisAG",
  "DakariJohnson",
  "Aaron_White30",
  "YoungTRaaw",
  "hellosatnam",
  "Sirdom1",
  "danidiez11",
  "Lac25_",
  "nikoradicevic",
  "AirPierreTokoto",
  "mitar_mitar9",
  "Ryanboatright11",
  "Mauricendure",
  "IamFelicio",
  "shyxxm",
  "UPSHAW50",
  "CAlexander",
  "MelvinEjim",
  "_TP5",
  "TJMcConnell",
  "scottiew_5",
  "AaronICE2",
  "Chriswood_5",
  "BobanMarjanovic",
  "ThaRealJsimms",
  "MichaleKyser",
  "toups_33",
  "3SScott",
  "MrFamous_CME",
  "50Mejri",
  "TerricoWhite5",
  "TreBall21",
  "LeviRandolph20",
  "MalcMili13",
  "MickeyMcConnell",
  "phillybul_22",
  "lilmu2",
  "M_Pressive3",
  "LCSikma43",
  "MikeStock20",
  "Jholland_23",
  "RyT5",
  "Jpullz0",
  "mjanning23",
  "jgiblife",
  "Zeek_Jones11",
  "Bryant_Dunston",
  "SDennis14",
  "Gstutz41",
  "MONT_MACK",
  "Macmainstreet",
  "zaygibson",
  "2_E_A_Z_Y",
  "O_Ash",
  "foe23",
  "prichard_3",
  "VeEG00D",
  "MichaelSnaer21",
  "KingKK_14",
  "2cooltone",
  "ROEOSBY24",
  "jberggren40",
  "Im_Keithclanton",
  "GlenDandridgeJr",
  "ajslaughter8",
  "YeahRod24",
  "KhalifW05",
  "TMbakwe32",
  "jaygranger11",
  "timabro21",
  "DaJuice55",
  "TPeterson42",
  "KorieLucious",
  "EJSingler",
  "JamelleHagins",
  "MyckK9",
  "DarknessRises17",
  "Jackie_C32",
  "Amath22Juice",
  "RasidMahalbasic",
  "rodneygreen10",
  "Lo_Tatted",
  "TooTall2KnoSo1",
  "bjyoung_money11",
  "ncsu_cleslie",
  "EVargas30",
  "TheLiamMcMorrow",
  "MaxOnTwitter",
  "Ziggy_Marsh",
  "ScottWood15",
  "KadjiKenneth",
  "vitaminDseeley",
  "Gaddy253_",
  "durand_scott",
  "ANT_MARZ3",
  "BrandonTriche",
  "21zachandrews",
  "Lg5live",
  "KB33_",
  "cjharris11",
  "Anosike_1",
  "LBowers_21",
  "GRJR22",
  "paranhos_24",
  "ChampOguchi",
  "ChaceStanback",
  "T_2releFOUR",
  "scottro15",
  "ChapFTW",
  "JMTaylor11",
  "DevinBooker31",
  "Adrlawrence",
  "LordSuttonJr",
  "JRwontLOSE",
  "mbruesewitz31",
  "BadenJaxen_",
  "scoopjardine",
  "RickyHarris5",
  "KeydrenClark",
  "BP3",
  "tomabo10",
  "jacohen15",
  "T_Lockett24",
  "cjaiken01",
  "Da_Thrill21",
  "KRandy_12",
  "Aminu_34",
  "2easy32",
  "Huertas09",
  "Wiggys__WORLD",
  "Horford4rep",
  "egwu_32",
  "Smooth_Jordan",
  "holybigfella",
  "DanielNwaelele",
  "DSweetney1",
  "Edgarsosa10",
  "cwebster9",
  "willcummings_",
  "denzel_trey10",
  "kingsky23",
  "BLOCKchynski",
  "TreKel1ey",
  "Built4Bucketz",
  "QCook323",
  "Ttrice20",
  "yndoye35",
  "ksykesyb",
  "Mr_WALKONAIR",
  "_DezWells",
  "SlamIAm12",
  "jaywash42",
  "BegicMirzaBM",
  "Sir_deuce2",
  "dofboyfresh34",
  "smoothlikeju",
  "The1_MikeCobbs",
  "EAtkins0",
  "alantwilliams",
  "xaviermunford",
  "Papi_Fells",
  "BenSimmons25",
  "B_Ingram13",
  "DBender03",
  "KrisDunn3",
  "buddyhield",
  "BeMore27",
  "quese",
  "JakobPoeltl",
  "Dsabonis11",
  "taureanprince",
  "G_P_06",
  "denzelvalentine",
  "juanchiviris41",
  "DTP_Mario",
  "The_Fourth_Wade",
  "HenryEllenson13",
  "Mb5Malik",
  "CarisLeVert",
  "fearthefro95",
  "KingMali23",
  "Ante__Zizic",
  "bjohnson_23",
  "FurkanKorkmaz",
  "pskills43",
  "OneBigHaitian",
  "DejounteMurray",
  "dameology",
  "DeyontaDavis_04",
  "ivicazubac",
  "cheick_diallo13",
  "tulis3",
  "zagorac_rade",
  "MalcolmBrogdon7",
  "chinanu_onuaku",
  "PMcCaw0",
  "Diamond_Stone33",
  "BIGG_ZIMM",
  "isaiahwhitehead",
  "officialzhouqi",
  "izaycordinier",
  "D_Jay11",
  "JLayman10",
  "paulzzip",
  "mikegbinije",
  "GeorgesNiang20",
  "benbentil",
  "Bolomboy21",
  "marcuspaige5",
  "AbdelNader2",
  "TyWallace661",
  "marshallplumlee",
  "MKuzminskas",
  "StefanJ33",
  "doefinney_10",
  "owhite10",
  "DanuelHouseJr",
  "nicoobrussino",
  "RyArch15",
  "BrynjForbes",
  "FredVanVleet",
  "MattCostello10",
  "bigrussia5",
  "Egidijus55",
  "KHornsby4",
  "Fullcoursemeelz",
  "YogiFerrell11",
  "sheldonmacc",
  "beaubeech02",
  "miketobey10",
  "TimQuarterman1",
  "patitogarino",
  "RonBaker31",
  "troywilliams_",
  "Mr_Uthoff",
  "WayneSeldenJr",
  "ChassonRandle",
  "Ymoreira02",
  "GTMGH3",
  "AlexTheGreat22",
  "ZachEliAuguste",
  "catbarber1994",
  "Drew_squared",
  "sheed_ctmd1",
  "n_zeis2",
  "Qman_12",
  "DSR43",
  "Nik_Jovanovic",
  "C_Will21",
  "Dami0nLee",
  "NotLilJay",
  "TheRea1DJones",
  "kwiltj",
  "Zay_Ctmd11",
  "ACFresh21",
  "twalkup23",
  "nicolapro7",
  "gbakumanya",
  "DCookeJr",
  "joshmagette",
  "vashilluv_bball",
  "mamadoundiaye14",
  "LBgetbuckets02",
  "dnwaba0",
  "MarkelleF",
  "ZO2_",
  "jaytatum0",
  "j_josh11",
  "swipathefox",
  "JJudahIsaac",
  "MarkkanenLauri",
  "FrankLikina",
  "Dennis1SmithJr",
  "AhmadMonk",
  "LukeKennard5",
  "spidadmitchell"
];

module.exports = { INJURIES, twitterAccounts };
