const INJURIES = [
  {
    id: "27",
    Name: "Bruised Knee",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Athleticism",
  },
  {
    id: "30",
    Name: "Bruised Shoulder",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
  },
  {
    id: "32",
    Name: "Bruised Tailbone",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
  },
  {
    id: "61",
    Name: "Hyperextended Knee",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding, Athleticism",
  },
  {
    id: "60",
    Name: "Hyperextended Elbow",
    DurationMin: 3,
    DurationMax: 8,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
  },
  {
    id: "66",
    Name: "Leg Cramp",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Shooting",
    AffectedHigh: "Athleticism"
  },
  {
    id: "70",
    Name: "Migraine",
    DurationMin: 4,
    DurationMax: 7,
    AffectedLow: "Shooting, Rebounding, Post Game, Driving Layup",
    AffectedHigh: "Playmaking, Offensive Consistency,",
    DNP: true
  },
  {
    id: "71",
    Name: "Neck Spasms",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding, Athleticism",
  },
  {
    id: "75",
    Name: "Pinched Elbow Nerve",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
  },
  {
    id: "77",
    Name: "Pinched Shoulder Nerve",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
  },
  {
    id: "78",
    Name: "Plantar Fasciitis",
    DurationMin: 8,
    DurationMax: 12,
    AffectedLow: "Finishing, Post Game, Athleticism",
  },
  {
    id: "85",
    Name: "Shoulder Tendinitis",
    DurationMin: 4,
    DurationMax: 8,
    AffectedLow: "Shooting, Post Game, Finishing, Stocks, Rebounding,",
  },
  {
    id: "86",
    Name: "Sore Ankle",
    DurationMin: 2,
    DurationMax: 4,
    AffectedLow: "Shooting, Post Game",
    AffectedHigh: "Finishing, Athletiicsm",
    DNP: true,
  },
  {
    id: "89",
    Name: "Sore Hamstring",
    DurationMin: 2,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
    AffectedHigh: "Athleticism",
    DNP: true,
  },
  {
    id: "91",
    Name: "Sore Knee",
    DurationMin: 2,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
    AffectedHigh: "Athleticism",
    DNP: true,
  },
  {
    id: "93",
    Name: "Sore Wrist",
    DurationMin: 4,
    DurationMax: 8,
    AffectedLow: "Finishing, Shooting, Post Game",
  },
  {
    id: "96",
    Name: "Sprained Elbow",
    DurationMin: 4,
    DurationMax: 9,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
  },
  {
    id: "104",
    Name: "Strained Achilles",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Athleticism",
  },
  {
    id: "109",
    Name: "Strained MCL",
    DurationMin: 3,
    DurationMax: 6,
    AffectedLow: "Finishing, Shooting, Post Game, Stocks, Rebounding",
    AffectedHigh: "Athleticism",
  },
];